### ISSUE TITLE
How to exclude the ".git" folder

### ISSUE THREAD

**Issue by didoo** [neonious/lowsync#1]
I am trying to use the "exclude" parameter in the config file to avoid uploading the _.git_ folder to the Neonios. This is my current configuration:
```
{
    "ip": "192.168.1.192",
    "syncDir": "Neonious",
    "useHttp": true,
    "exclude": [
        ".git"
    ]
}
```
but apparently it doesn't work. This is the result:
<img width="583" alt="snapshot_1466" src="https://user-images.githubusercontent.com/686239/56468565-4de68a80-6426-11e9-8eba-7bd9dd9efce6.png">
<img width="593" alt="snapshot_1467" src="https://user-images.githubusercontent.com/686239/56468578-54750200-6426-11e9-8ee9-7c8439adc9c0.png">

Something that I am doing wrong?

**Comment by neoniousTR** [comment]
Where did you find the documentation for the exclude option? I am not sure if we implemented this.

See https://github.com/neonious/lowsync/issues/3:
We will do a simple fix to this and exclude files/folders with a . in an update in the next week.

**Comment by didoo** [comment]
@neoniousTR here: https://www.lowjs.org/lowsync-doc/configuration.html

<img width="745" alt="snapshot_1474" src="https://user-images.githubusercontent.com/686239/58277012-afd14180-7d90-11e9-8e7a-c6646fc5b6ec.png">

**Comment by neoniousTR** [comment]
Oh I understand. Will try to figure out the problem next week.
