### ISSUE TITLE
Flashing on WSL requires port option rts to be true

### ISSUE THREAD

**Issue by cascornelissen** [neonious/lowsync#11]
As a follow-up on #9, not sure if this a bug within `lowsync` but I wanted to report it here anyway since someone else might run into this as well. I'm aiming to flash an ESP32 WROVER from WSL1 (WSL2 does not support serial interfaces yet) running Debian.

While trying to flash an ESP32 WROVER-B I, again. ran into the same error:

```
$ node_modules/.bin/lowsync flash --port=/dev/ttyS4 --init
*** Step 1/3: Probing ESP32 microcontroller
    now checking if it is an ESP32-WROVER... (takes a while)
Unexpected error: Error: Inappropriate ioctl for device, cannot set Error: Error: Inappropriate ioctl for device, cannot set
```

Commenting out the following line, basically keeping `'rts'` option `true`, fixes this issue and flashes the ESP32 correctly.

https://github.com/neonious/lowsync/blob/00c735eb53584d37a5d3faa1781472dba75098bc/src/commands/commands/flash.ts#L50

Again, not sure if this is an actual bug withing `lowsync` so feel free to close this issue (and hopefully provide some more details on why it isn't). If there's anything I can do to debug this further, let me know!

**Comment by neoniousTR** [comment]
This is weird... If rts=1, dtr=0 is kept, then the chip should stay in reset and not run the check_wrover program. So in my opinion it should not work when  port.set({'rts': false, 'dtr': false});  is removed.

Not sure how to continue with this..

**Comment by cascornelissen** [comment]
That's what I was thinking as well, it's the only way to get it working on my end though 🤷🏼‍♂️ That's why I opened a bug report, feel free to close it if you want to, at least people with similar problems can hopefully find some more info/ideas on this now.

If there's anything I can do to debug this further let me know as well.
