### ISSUE TITLE
lowsync for ESP32-D2WD? (2MiB Flash)

### ISSUE THREAD

**Issue by zrecore** [neonious/lowsync#2]
I'm just now learning about your amazing low.js project, amazing work! As I am still unfamiliar with the inner workings, may I ask what it would take (if possible) to make this tool work with the ESP32-D2WD chip? It has 2MiB of Flash built in.

**Comment by neoniousTR** [comment]
Not possible, sorry :-) You need 4 MB PSRAM which it does not have.

**Comment by zrecore** [comment]
Ah ok. Thank you for letting me know.
