### ISSUE TITLE
.vscode dir causes sync error

### ISSUE THREAD

**Issue by mmende** [neonious/lowsync#3]
I encountered an error when trying to sync. The error message was unfortunately truncated to
 `An error has occured: Error syncing file/folder to the microcontroller. Could no`
However I added an additional log in `src/commands/commands/sync/synchronize/syncFile.ts` at line 281 to see the full error message starting with
`Error: Could not create directory at /.vscode. Http error: MKCOL`
After simply deleting the .vscode directory the syncing worked perfectly fine so the problem might have to do with the dot in front of the directory name. It might be a good idea to simply exclude directories with leading dot from sync.

However thanks for the awesome work.

**Comment by neoniousTR** [comment]
We will do a simple fix to this and exclude files/folders with a . in an update in the next week.
Thank you!
