### ISSUE TITLE
Error while trying to install npm packages

### ISSUE THREAD

**Issue by gilsonvarghese27** [neonious/lowsync#4]
I was trying to install asw-sdk using `lowsync install aws-sdk`
I get the error
`~/esp32/lowjs/node_modules/lowsync/build/webpack:/src/pkgman/addRemove.ts:71
            const { stage, message } = JSON.parse(serverRawBody);
                                            ^
SyntaxError: Unexpected token e in JSON at position 0
`
What would be the possible cause? I get the same issue while installing mqtt.

**Comment by neoniousTR** [comment]
Thank you for the report. Interesting. Should be fixable as it is easily reproducable. I will take a look this week.

**Comment by neoniousTR** [comment]
OK, if you update to lowsync 1.0.24 and flash a new lowjs firmware the error message should now be correct. I expect the error to be "insufficient space left on device". aws-sdk is a beast. mqtt however is not, around 1.5 MB, but that is too much for a generic ESP32-WROVER board. Maybe you want to get a neonious one? Here mqtt works, tested it now.

**Comment by neoniousTR** [comment]
Additional note:
If you are already using a neonious one, the update fixes a bug where installing mqtt after a try of aws-sdk would not work. So just retry after a firmware update.

**Comment by gilsonvarghese27** [comment]
@neoniousTR Thank you for the reply. I use ESP32-WROVER kit. I assume, it has 8mb psram. I will try installing it again with latest version. Could you please tell me, if lowjs has any provision for knowing hardware details like RAM or flash capabilities?

**Comment by neoniousTR** [comment]
RAM is not the issue, it is Flash disk space. The classic WROVER only has 4 MB Flash, and lowjs currently needs 3 MB. If you have the 16 MB version, you get 13 MB, which is more than enough.

Please check:
console.log(JSON.stringify(require('lowsys').partitions.flash, null, 2));

What are you actually trying to do? Is it fun or business? If second, we can give in depth support, just contact info@neonious.com

**Comment by gilsonvarghese27** [comment]
Hi @neoniousTR ,
I was actually trying to check bluetooth and aws iot with lowjs. I ran the command and got {
  "used": 34638,
  "size": 956561
 }
which means 1MB flash.
However if I run esptool, I get:

Device: 4016
Detected flash size: 4MB.

**Comment by neoniousTR** [comment]
That is exactly what I said in the last post: 4 MB - 3 MB = 1 MB
So, everything is correct.

Closing. If you see a problem, please tell, and I will reopen.

**Comment by gilsonvarghese27** [comment]
I was wondering if I would be able to use microsd for the same. @neoniousTR  If I add a microsd card will it use for installing node modules?
