### ISSUE TITLE
Setting environment variable from lowsync command

### ISSUE THREAD

**Issue by gilson27** [neonious/lowsync#6]
Does lowsync support setting process.env other than from from application code?

**Comment by neoniousTR** [comment]
Environment variables are a concept of a desktop UI. We have not seen them as relevant for embedded.
If a module does not work with the right settings, a

process.env = JSON.parse(require('/env.json'));

as the first line of your main program file should allow you to set any settings you wish based on a env.json file you provide.

Does this solve your problem?

**Comment by gilson27** [comment]
Yes. Thank you.
